In [2]:
import numpy as np
import pandas as pd
import matplotlib as mp
import seaborn as sns
import matplotlib.pyplot as plt

#import raw dataset
df = pd.read_csv("/Users/maurits/Documents/Ironhack/week_03/GPW3/ironhack_gpw3/data/combined_dataset_allyears.csv")
df.head(10)

,City Boundary Specification (LAU/grid),Country Or Territory,City,City Code,Total City Population *,Year,Air Pollutant,Health Risk Scenario,Populated Area [km2],Air Pollution Average [ug/m3],Air Pollution Population Weighted Average [ug/m3],Premature Deaths,Premature Deaths - lower CI,Premature Deaths - upper CI,Years Of Life Lost,Years Of Life Lost - lower CI,Years Of Life Lost - upper CI
0,Urban Centres (grid),Austria,All Urban Centres in a Country,NaN,2405646,2005,NO2,WHO_2005_HRAPIE_Scen_Base,446,30.3,32.8,1352.0,783.0,1911.0,14704.0,8522.0,20791.0
1,Urban Centres (grid),Belgium,All Urban Centres in a Country,NaN,3030639,2005,NO2,WHO_2005_HRAPIE_Scen_Base,745,32.4,35.1,2141.0,1247.0,3017.0,22939.0,13338.0,32327.0
2,Urban Centres (grid),Bulgaria,All Urban Centres in a Country,NaN,3010927,2005,NO2,WHO_2005_HRAPIE_Scen_Base,384,23.3,24.9,1236.0,712.0,1759.0,13367.0,7713.0,18982.0
3,Urban Centres (grid),Cyprus,All Urban Centres in a Country,NaN,418267,2005,NO2,WHO_2005_HRAPIE_Scen_Base,131,20.3,21.0,24.0,13.0,34.0,249.0,143.0,357.0
4,Urban Centres (grid),Czechia,All Urban Centres in a Country,NaN,2464143,2005,NO2,WHO_2005_HRAPIE_Scen_Base,536,26.4,27.6,961.0,554.0,1364.0,10585.0,6105.0,15045.0
5,Urban Centres (grid),Germany,All Urban Centres in a Country,NaN,25479567,2005,NO2,WHO_2005_HRAPIE_Scen_Base,6769,29.2,30.7,13555.0,7850.0,19178.0,152916.0,88550.0,216447.0
6,Urban Centres (grid),Denmark,All Urban Centres in a Country,NaN,1490619,2005,NO2,WHO_2005_HRAPIE_Scen_Base,400,22.5,24.1,341.0,197.0,487.0,3757.0,2159.0,5354.0
7,Urban Centres (grid),Estonia,All Urban Centres in a Country,NaN,522560,2005,NO2,WHO_2005_HRAPIE_Scen_Base,103,16.4,17.4,5.0,3.0,7.0,54.0,31.0,78.0
8,Urban Centres (grid),Spain,All Urban Centres in a Country,NaN,21279144,2005,NO2,WHO_2005_HRAPIE_Scen_Base,2439,29.8,34.3,13055.0,7618.0,18337.0,143218.0,83571.0,201141.0
9,Urban Centres (grid),European Union Countries,All Urban Centres in EU27,NaN,145177261,2005,NO2,WHO_2005_HRAPIE_Scen_Base,29537,29.3,32.1,81424.0,47430.0,114554.0,907395.0,528454.0,1276934.0

In [3]:
######## PART 1: DATA CLEANING ########

# CLEANING TECHNIQUES:

# 1. concatenate datasets DONE
# 2. rename columns: replace white spaces with underscores DONE
# 3. replace null values in column premature deaths with appropriate values DONE*
# 4. remove duplicated rows (if any)
# 5. remove redundant columns
# 6. handle null values
# 7. reset index

#* might need some attention

In [4]:
# 2. lowercase column names and replace white spaces for underscores.

df.columns = [col.replace(" ","_").lower() for col in df.columns]

In [5]:
# column_names = list([df.columns])
column_names = df.columns.tolist()
column_names

['city_boundary_specification_(lau/grid)',
 'country_or_territory',
 'city',
 'city_code',
 'total_city_population_*',
 'year',
 'air_pollutant',
 'health_risk_scenario',
 'populated_area_[km2]',
 'air_pollution_average_[ug/m3]',
 'air_pollution_population_weighted_average_[ug/m3]',
 'premature_deaths',
 'premature_deaths_-_lower_ci',
 'premature_deaths_-_upper_ci',
 'years_of_life_lost',
 'years_of_life_lost_-_lower_ci',
 'years_of_life_lost_-_upper_ci']

In [6]:
column_names[-6:]

['premature_deaths',
 'premature_deaths_-_lower_ci',
 'premature_deaths_-_upper_ci',
 'years_of_life_lost',
 'years_of_life_lost_-_lower_ci',
 'years_of_life_lost_-_upper_ci']

In [7]:
columns_to_check = column_names[-6:]
rows_with_null_values = df[columns_to_check].isnull().all(axis=1)
years_countries = df.loc[rows_with_null_values, ['country_or_territory', 'year']]
print(years_countries)


years_countries.describe()

       country_or_territory  year
56                  Austria  2005
57                  Belgium  2005
58                 Bulgaria  2005
59                   Cyprus  2005
60                  Czechia  2005
...                     ...   ...
226583             Slovakia  2019
226590             Slovakia  2020
226594             Slovakia  2020
226601             Slovakia  2021
226605             Slovakia  2021

[49708 rows x 2 columns]

               year
count  49708.000000
mean    2013.000000
std        4.899029
min     2005.000000
25%     2009.000000
50%     2013.000000
75%     2017.000000
max     2021.000000

In [8]:
# Fill NaN in premature deaths with mean, sort by city and year

def fill_na_with_group_mean(group):
    return group.fillna(group.mean())

df['premature_deaths'] = df.groupby(['city', 'year'])['premature_deaths'].transform(fill_na_with_group_mean)

df['premature_deaths']
df_mean = df
df_mean['premature_deaths']

0         1352.0
1         2141.0
2         1236.0
3           24.0
4          961.0
           ...
226605      31.0
226606      63.0
226607      22.0
226608      17.0
226609      91.0
Name: premature_deaths, Length: 226610, dtype: float64

In [9]:
# Check with an appopriate visualisation method which aggregation method is most appropriate (mean or median).

In [10]:
# Fill NaN in premature deaths with median, sort by city and year

def fill_na_with_group_median(group):
    return group.fillna(group.median())

df['years_of_life_lost'] = df.groupby(['city', 'year'])['years_of_life_lost'].transform(fill_na_with_group_median)

In [11]:
# Fill NaN in premature deaths with median, sort by city and year

def fill_na_with_group_median(group):
    return group.fillna(group.median())

df['premature_deaths'] = df.groupby(['city', 'year'])['premature_deaths'].transform(fill_na_with_group_median)

In [12]:
# Potentially use this code to fill in NaN in ci columns

def fill_na_with_group_median(group):
    return group.fillna(group.median())

df['premature_deaths_-_lower_ci'] = df.groupby(['city', 'year'])['premature_deaths_-_lower_ci'].transform(fill_na_with_group_median)

In [13]:
def fill_na_with_group_median(group):
    return group.fillna(group.median())

df['premature_deaths_-_upper_ci'] = df.groupby(['city', 'year'])['premature_deaths_-_upper_ci'].transform(fill_na_with_group_median)

In [14]:
def fill_na_with_group_median(group):
    return group.fillna(group.median())

df['years_of_life_lost_-_lower_ci'] = df.groupby(['city', 'year'])['years_of_life_lost_-_lower_ci'].transform(fill_na_with_group_median)

In [15]:
def fill_na_with_group_median(group):
    return group.fillna(group.median())

df['years_of_life_lost_-_upper_ci'] = df.groupby(['city', 'year'])['years_of_life_lost_-_upper_ci'].transform(fill_na_with_group_median)

In [16]:
df.isna().sum()

city_boundary_specification_(lau/grid)                  0
country_or_territory                                    0
city                                                    0
city_code                                            4340
total_city_population_*                                 0
year                                                    0
air_pollutant                                           0
health_risk_scenario                                    0
populated_area_[km2]                                    0
air_pollution_average_[ug/m3]                           0
air_pollution_population_weighted_average_[ug/m3]       0
premature_deaths                                        0
premature_deaths_-_lower_ci                             0
premature_deaths_-_upper_ci                             0
years_of_life_lost                                      0
years_of_life_lost_-_lower_ci                           0
years_of_life_lost_-_upper_ci                           0
dtype: int64

In [17]:
# 3. remove duplicated rows (if any). Check: there were zero duplicated rows, nothing to remove.
df.duplicated().sum()

np.int64(0)

In [18]:
# column removal: city_code

df = df.drop('city_code', axis=1)

In [19]:
# Reset the index
df = df.reset_index(drop=True)
df

,city_boundary_specification_(lau/grid),country_or_territory,city,total_city_population_*,year,air_pollutant,health_risk_scenario,populated_area_[km2],air_pollution_average_[ug/m3],air_pollution_population_weighted_average_[ug/m3],premature_deaths,premature_deaths_-_lower_ci,premature_deaths_-_upper_ci,years_of_life_lost,years_of_life_lost_-_lower_ci,years_of_life_lost_-_upper_ci
0,Urban Centres (grid),Austria,All Urban Centres in a Country,2405646,2005,NO2,WHO_2005_HRAPIE_Scen_Base,446,30.3,32.8,1352.0,783.0,1911.0,14704.0,8522.0,20791.0
1,Urban Centres (grid),Belgium,All Urban Centres in a Country,3030639,2005,NO2,WHO_2005_HRAPIE_Scen_Base,745,32.4,35.1,2141.0,1247.0,3017.0,22939.0,13338.0,32327.0
2,Urban Centres (grid),Bulgaria,All Urban Centres in a Country,3010927,2005,NO2,WHO_2005_HRAPIE_Scen_Base,384,23.3,24.9,1236.0,712.0,1759.0,13367.0,7713.0,18982.0
3,Urban Centres (grid),Cyprus,All Urban Centres in a Country,418267,2005,NO2,WHO_2005_HRAPIE_Scen_Base,131,20.3,21.0,24.0,13.0,34.0,249.0,143.0,357.0
4,Urban Centres (grid),Czechia,All Urban Centres in a Country,2464143,2005,NO2,WHO_2005_HRAPIE_Scen_Base,536,26.4,27.6,961.0,554.0,1364.0,10585.0,6105.0,15045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226605,ESTAT Urban Audit Cities (LAU),Slovakia,Trencín,62655,2021,PM10,WHO_2021_AQG_Scen_Base,64,18.8,20.1,31.0,11.0,21.0,194.0,121.0,235.0
226606,ESTAT Urban Audit Cities (LAU),Slovakia,Trencín,62655,2021,PM2.5,WHO_2021_AQG_Scen_Base,64,14.5,15.6,63.0,48.0,70.0,678.0,519.0,756.0
226607,ESTAT Urban Audit Cities (LAU),Slovakia,Trencín,62655,2021,NO2,WHO_2021_AQG_Scen_Sensitivity_2,64,10.7,14.1,22.0,11.0,43.0,238.0,121.0,466.0
226608,ESTAT Urban Audit Cities (LAU),Slovakia,Trencín,62655,2021,O3,WHO_2021_AQG_Scen_Sensitivity_2,64,19308.1,18276.6,17.0,14.0,21.0,194.0,154.0,235.0
226609,ESTAT Urban Audit Cities (LAU),Slovakia,Trencín,62655,2021,PM2.5,WHO_2021_AQG_Scen_Sensitivity_2,64,14.5,15.6,91.0,70.0,101.0,980.0,753.0,1090.0

In [21]:
# Adding a density column to the dataset
df['density'] = df['total_city_population_*']/df['populated_area_[km2]']
df.head()

,city_boundary_specification_(lau/grid),country_or_territory,city,total_city_population_*,year,air_pollutant,health_risk_scenario,populated_area_[km2],air_pollution_average_[ug/m3],air_pollution_population_weighted_average_[ug/m3],premature_deaths,premature_deaths_-_lower_ci,premature_deaths_-_upper_ci,years_of_life_lost,years_of_life_lost_-_lower_ci,years_of_life_lost_-_upper_ci,density
0,Urban Centres (grid),Austria,All Urban Centres in a Country,2405646,2005,NO2,WHO_2005_HRAPIE_Scen_Base,446,30.3,32.8,1352.0,783.0,1911.0,14704.0,8522.0,20791.0,5393.825112
1,Urban Centres (grid),Belgium,All Urban Centres in a Country,3030639,2005,NO2,WHO_2005_HRAPIE_Scen_Base,745,32.4,35.1,2141.0,1247.0,3017.0,22939.0,13338.0,32327.0,4067.971812
2,Urban Centres (grid),Bulgaria,All Urban Centres in a Country,3010927,2005,NO2,WHO_2005_HRAPIE_Scen_Base,384,23.3,24.9,1236.0,712.0,1759.0,13367.0,7713.0,18982.0,7840.955729
3,Urban Centres (grid),Cyprus,All Urban Centres in a Country,418267,2005,NO2,WHO_2005_HRAPIE_Scen_Base,131,20.3,21.0,24.0,13.0,34.0,249.0,143.0,357.0,3192.877863
4,Urban Centres (grid),Czechia,All Urban Centres in a Country,2464143,2005,NO2,WHO_2005_HRAPIE_Scen_Base,536,26.4,27.6,961.0,554.0,1364.0,10585.0,6105.0,15045.0,4597.281716

In [25]:
# Filtering on only PM 2.5 pollutants
df_filtered = df[df['air_pollutant'] == 'PM2.5'] 
df_filtered.head()

,city_boundary_specification_(lau/grid),country_or_territory,city,total_city_population_*,year,air_pollutant,health_risk_scenario,populated_area_[km2],air_pollution_average_[ug/m3],air_pollution_population_weighted_average_[ug/m3],premature_deaths,premature_deaths_-_lower_ci,premature_deaths_-_upper_ci,years_of_life_lost,years_of_life_lost_-_lower_ci,years_of_life_lost_-_upper_ci,density
84,Urban Centres (grid),Austria,All Urban Centres in a Country,2405646,2005,PM2.5,WHO_2005_HRAPIE_Scen_Base,446,21.6,22.0,2532.0,1687.0,3287.0,27563.0,18385.0,35772.0,5393.825112
85,Urban Centres (grid),Belgium,All Urban Centres in a Country,3030639,2005,PM2.5,WHO_2005_HRAPIE_Scen_Base,745,19.0,19.3,3025.0,2013.0,3936.0,32439.0,21580.0,42208.0,4067.971812
86,Urban Centres (grid),Bulgaria,All Urban Centres in a Country,3010927,2005,PM2.5,WHO_2005_HRAPIE_Scen_Base,384,34.2,34.6,7927.0,5363.0,10157.0,85612.0,57929.0,109669.0,7840.955729
87,Urban Centres (grid),Cyprus,All Urban Centres in a Country,418267,2005,PM2.5,WHO_2005_HRAPIE_Scen_Base,131,29.5,29.6,460.0,310.0,592.0,4835.0,3249.0,6231.0,3192.877863
88,Urban Centres (grid),Czechia,All Urban Centres in a Country,2464143,2005,PM2.5,WHO_2005_HRAPIE_Scen_Base,536,24.4,24.6,3330.0,2231.0,4315.0,36733.0,24581.0,47529.0,4597.281716

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226610 entries, 0 to 226609
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   city_boundary_specification_(lau/grid)             226610 non-null  object
 1   country_or_territory                               226610 non-null  object
 2   city                                               226610 non-null  object
 3   total_city_population_*                            226610 non-null  int64
 4   year                                               226610 non-null  int64
 5   air_pollutant                                      226610 non-null  object
 6   health_risk_scenario                               226610 non-null  object
 7   populated_area_[km2]                               226610 non-null  int64
 8   air_pollution_average_[ug/m3]                      226610 non-null  float64
 9   air_pollution_population_weighted_average_[ug/m3]  226610 non-null  float64
 10  premature_deaths                                   226610 non-null  float64
 11  premature_deaths_-_lower_ci                        226610 non-null  float64
 12  premature_deaths_-_upper_ci                        226610 non-null  float64
 13  years_of_life_lost                                 226610 non-null  float64
 14  years_of_life_lost_-_lower_ci                      226610 non-null  float64
 15  years_of_life_lost_-_upper_ci                      226610 non-null  float64
 16  density                                            226610 non-null  float64
dtypes: float64(9), int64(3), object(5)
memory usage: 29.4+ MB

In [ ]:
# exporting dataset to CSV
# df.to_csv('cleaned_combined_dataset_density.csv', index=False)

In [ ]:
#import cleaned and filtered dataset
df = pd.read_csv("/Users/maurits/Documents/Ironhack/week_03/GPW3/ironhack_gpw3/data/cleaned/cleaned_combined_dataset_filtered.csv")
df.head(10)

In [ ]:
#import cleaned and filtered dataset
df = pd.read_csv("/Users/maurits/Documents/Ironhack/week_03/GPW3/ironhack_gpw3/data/cleaned/cleaned_combined_dataset_filtered.csv")
df.head(10)

In [1]:
#Creation graphs for 
df_small_dense = df[(df['total_city_population_*'] <= 250000) & (df['density'] >= 3000)]
df_small_nondense = df[(df['total_city_population_*'] <= 250000) & (df['density'] <= 3000)]
df_large_dense = df[(df['total_city_population_*'] >= 1000000) & (df['density'] >= 3000)]
df_large_nondense = df[(df['total_city_population_*'] >= 1000000) & (df['density'] <= 3000)]
df_small_dense_pmd = df[(df['total_city_population_*'] <= 250000) & (df['density'] >= 3000)]
df_small_nondense_pmd = df[(df['total_city_population_*'] <= 250000) & (df['density'] <= 3000)]
df_large_dense_pmd = df[(df['total_city_population_*'] >= 1000000) & (df['density'] >= 3000)]
df_large_nondense_pmd = df[(df['total_city_population_*'] >= 1000000) & (df['density'] <= 3000)]

NameError: name 'df' is not defined